### PR TITLE
Fix regular pods on preemptible node are deleted immediately

### PR DESCRIPTION
**Pull request by na-ga**
Reserve time for system pods if regular pods have adequate time to exit gracefully. Otherwise, GracePeriodSeconds for regular pods is set to an initial value (zero). Setting GracePeriodSeconds to zero means delete immediately.

If the target node is a preemptibe, the timeout to evict pod is 30 seconds. And the default value of the `--system-pod-grace-period` command-line flag is 30 seconds. Therefore, when a preempted event is subscribed, the regular pod is immediately delete with no grace period.

I think the regular pods need time to exit gracefully. Fix specified timeout to be used in GracePeriodSeconds for regular pods if the regular pod doesn't have adequate time to exit gracefully.

### CODE REVIEW

**Comment by na-ga** [comment]
@googlebot I signed it!

**Comment by na-ga** [comment]
@googlebot I signed it!

**Comment by na-ga** [comment]
@googlebot I signed it!

**Comment by na-ga** [comment]
I had a discussion with @namusyaka.

I thought this tool delete regular pods with GracePeriodSeconds=30 and then delete system pod with the remaining grace time. 

As the original author comments, "This is especially helpful in scenarios like reclaiming logs prior to node termination", this tool ensure graceful shutdown of the pods under the `kube-system` namespace. So, I understand that this tool is an implementation that prioritizes system pods over regular pods.

I think there are times when I want to give regular pods some grace time rather than the immediate deletion behavior of regular pods. Since the preemptible node has a grace period of 30 seconds, I would like to use this tool to specify `-system-pod-grace-period=10` on the command line and the regular pod has the remaining about 20 seconds.

Thanks.

**Comment by namusyaka** [comment]
Hi there,
@na-ga Thanks for your effort and the report.

@mindprince As he said above, if you're specifing 10 in system-pod-grace-period, the grace period for regular pods deletion will be 20s because the preemptible VM's timeout is 30s.
I guess the workaround he indicated goes well, but I'm not sure if the behavior would be understood intuitively because if the system-pod-grace-period is set to 20, the regular pods will be deleted immediately as `preemptible VM's timeout >= system-pod-grace-period * 2` is false in this case.

For the concern, is there any chance to add an option to specify a graceful period for regular pods deletion?

**Comment by yanc0** [comment]
I was wondering why my apps were so unstable when a preemption event occurs, even with this tool. I was pretty confused to see in the logs the `gracePeriodSeconds` parameter set to 0 on the "regular" pods:

```
About to delete pod "my-app-74cc8d96f6-bjn2p" in namespace "my-ns"
Request Body:{"kind":"DeleteOptions","apiVersion":"v1","gracePeriodSeconds":0} 
```
At least, this information should be documented on the README.md.

**Comment by namusyaka** [comment]
CC: @vishh

**Comment by namusyaka** [comment]
As per the conversation with David internally, we're now recognizing that the current behavior for regular pods termination makes users confusing a bit.
For the concerns, there are some options for getting rid of that, but we decided to work on the documentation at first. In the future, even if we'll adjust the default timeout value or add a new flag for handle this, we must take care of the backward compatibility.

@na-ga @yanc0 Thanks for your reports. Much appreciated.

**Pull request closed without merging**
